### ISSUE TITLE
App Transport Security and no images - only placeholders

### ISSUE THREAD

**Issue by kmav** [xmartlabs/XLData#11]
Using xcode 7.1/iOS8 and trying to open Remote Data Store Tableview, I got the message "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection". So I changed static NSString \* const APIBaseURLString = @"http://obscure-refuge-3149.herokuapp.com"; ... to https. Now I get the table view but instead of images there are only placeholders (default avatar).

![image](https://cloud.githubusercontent.com/assets/3893463/10798492/94282996-7db0-11e5-95b1-196f165f35fa.png)

Anyway I don't get images neither in Data Store TableView. Then inside I changed the images http with https and I got the images...

It seems that json is OK, BUT the returned links of images are http and not https ....

[{"user":{"id":1,"name":"Apu Nahasapeemapetilon","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Apu_Nahasapeemapetilon.png"}},{"user":{"id":7,"name":"Bart Simpsons","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Bart_Simpsons.png"}},{"user":{"id":8,"name":"Homer Simpsons","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Homer_Simpsons.png"}},{"user":{"id":9,"name":"Lisa Simpsons","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Lisa_Simpsons.png"}},{"user":{"id":2,"name":"Maggie Simpsons","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Maggie_Simpsons.png"}},{"user":{"id":3,"name":"Marge Simpsons","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Marge_Simpsons.png"}},{"user":{"id":4,"name":"Montgomery Burns","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Montgomery_Burns.png"}},{"user":{"id":5,"name":"Ned Flanders","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Ned_Flanders.png"}},{"user":{"id":6,"name":"Otto Mann","imageURL":"http://obscure-refuge-3149.herokuapp.com/images/Otto_Mann.png"}}]

Also the (http as well as https) images are there ... ![image](https://obscure-refuge-3149.herokuapp.com/images/Apu_Nahasapeemapetilon.png)

**Comment by mtnbarreto** [comment]
I've just fixed this issue. 
Thanks for reporting it.
