### ISSUE TITLE
Animation from XLData

### ISSUE THREAD

**Issue by ppaulojr** [xmartlabs/XLData#12]
After transitioning from [XLDataLoader](https://github.com/xmartlabs/XLDataLoader) to [XLData](https://github.com/xmartlabs/XLData), our table animations seems to be weird.

One hypothesis is that it's related to the way [XLData](https://github.com/xmartlabs/XLData) animates the `UITableViewCell` with `UITableViewRowAnimationAutomatic`

https://github.com/xmartlabs/XLData/blob/8b2023f8833f77112e0932e54f904ad69b015b6c/XLData/XL/Local/CoreData/XLCoreDataController.m#L224-L240

![output](https://cloud.githubusercontent.com/assets/1206478/11896600/0e476666-a56f-11e5-80b2-7649332e61ed.gif)

**Comment by itsaliu90** [comment]
@mtnbarreto @enrigalmig, please let us know about the above when you have a chance, thanks!

**Comment by mtnbarreto** [comment]
@yuningalexliu @ppaulojr 

As Pedro said this is because we are using `UITableViewRowAnimationAutomatic` as animation type whenever a cell is added or deleted.

I'm gonna add a extension point so we can customize it.

**Comment by itsaliu90** [comment]
Great, thanks so much Martin!

On Fri, Dec 18, 2015 at 3:35 PM, Martin Barreto notifications@github.com
wrote:

> @yuningalexliu https://github.com/yuningalexliu @ppaulojr
> https://github.com/ppaulojr
> 
> As Pedro said this is because we are using
> UITableViewRowAnimationAutomatic as animation type whenever a cell is
> added or deleted.
> 
> I'm gonna add a extension point so we can customize it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xmartlabs/XLData/issues/12#issuecomment-165892562.

## 

Alex Liu

_Here to help._

aliu@cipherhealth.com | 585.662.9096

CipherHealth http://www.cipherhealth.com/ | 555 8th Avenue, Suite 701,
New York, NY
_The information contained in this email message is intended only for the
use of the individual or the entity named above. If the reader of this
message is not the intended recipient, or the employee or agent responsible
for delivering it to the intended recipient, you are hereby notified that
any dissemination, distribution or copying of this communication is
strictly prohibited. If you have received this communication in error,
please immediately notify me by email (aliu@cipherhealth.com
aliu@cipherhealth.com), and destroy the original message. Thank you__._

**Comment by mtnbarreto** [comment]
@ppaulojr  The customization points were added. I also changed the move animation, now it's being performed using `[self.tableView moveRowAtIndexPath:indexPath toIndexPath:newIndexPath];`

Let me know if this fix the issue.

**Comment by ppaulojr** [comment]
Thank you @mtnbarreto 

https://github.com/xmartlabs/XLData/commit/d52dc4f3b381f6e3d365539fbd106aecdf9b352e fixed the problem
