### ISSUE TITLE
iOS 8.4 issue not refreshing data

### ISSUE THREAD

**Issue by ppaulojr** [xmartlabs/XLData#17]
In iOS 8.4 we have a problem that causes a table not to load completely in some circumstances when the following Assertion is triggered in XLData

``` objc
(*** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /SourceCache/UIKit_Sim/UIKit-3347.44.2/UITableView.m:1222)

(CoreData: error: Serious application error.  An exception was caught from the delegate of NSFetchedResultsController during a call to -controllerDidChangeContent:.  attempt to delete and reload the same index path (<NSIndexPath: 0x7e8bbc20> {length = 2, path = 0 - 0}) with userInfo (null))
```

It happens on:

``` objc
case NSFetchedResultsChangeUpdate:
     [self.tableView reloadRowsAtIndexPaths:@[indexPath] 
                         withRowAnimation:[self reloadRowAnimationForIndexPath:newIndexPath]];

```

And it's related to https://forums.developer.apple.com/thread/4999

@HelOlhausen fixed this on https://github.com/xmartlabs/XLData/blob/master/XLData/XL/Local/CoreData/XLCoreDataController.m#L234-L244 but the same workaround cannot be used for https://github.com/xmartlabs/XLData/blob/master/XLData/XL/Local/CoreData/XLCoreDataController.m#L245-L247

**Comment by ppaulojr** [comment]
Hint on fixing: https://gist.github.com/JohnEstropia/d7b25c11ba15564f0b16

**Comment by ppaulojr** [comment]
More info: http://stackoverflow.com/questions/31383760/ios-9-attempt-to-delete-and-reload-the-same-index-path and http://stackoverflow.com/questions/31383760/ios-9-attempt-to-delete-and-reload-the-same-index-path and https://openradar.appspot.com/22796598

**Comment by ppaulojr** [comment]
We still have the problem. Looking at the stack we see that the operation below:

``` objc
    @synchronized(self) {
        [self.mainQueueContext performBlock:^{
            // this ensures that changes to updated objects are also reflected in NSFetchedResultsControllers
            for(NSManagedObject *object in [[notification userInfo] objectForKey:NSUpdatedObjectsKey]) {
                [[self.mainQueueContext objectWithID:[object objectID]] willAccessValueForKey:nil];
            }
            [self.mainQueueContext mergeChangesFromContextDidSaveNotification:notification];
        }];
    }
```

Triggers this **XLData** code

``` objc
-(void)controllerDidChangeContent:(NSFetchedResultsController *)controller
{
    if (self.dataStoreControllerType == XLDataStoreControllerTypeTableView){
        [self tableViewEndUpdates];
    }
    else{
        [self collectionViewEndUpdates];
    }
    [self didChangeContent];
}
```

Which causes an `objc_exception_thrown`  at the line

```
        [self.tableView endUpdates];
```

In the method below:

``` objc
-(void)tableViewEndUpdates
{
    if (_beginUpdates){
        [self.tableView endUpdates];
        _beginUpdates = NO;
    }
}
```

The exception thrown is:

> Description of exception being thrown: 'attempt to delete and reload the same index path (<NSIndexPath: 0x7bfdf4e0> {length = 2, path = 0 - 0})'

In order to capture this exception you could set a symbolic breakpoint on the symbol `objc_exception_throw`.

**Comment by ppaulojr** [comment]
Additional notes. If you remove the code of `case NSFetchedResultsChangeMove:` you won't have this exception.

**Comment by mtnbarreto** [comment]
@ppaulojr Regarding your last point, this only works for this particular case and is not a general propuse solution. We should consider the move modification type.

**Comment by ppaulojr** [comment]
@mtnbarreto yes, for sure. I was just mentioning it because it seems to be there the problem.

**Comment by ppaulojr** [comment]
The commit 0fcd89b52e501d93a43e99b5f96b294cd0237157 fixed the problem. Thank you
