### ISSUE TITLE
Migration Guide for XLDataLoader

### ISSUE THREAD

**Issue by ppaulojr** [xmartlabs/XLData#9]
We were using [XLDataLoader](https://github.com/xmartlabs/XLDataLoader) in one of our applications and right now we are about to publish the last version that will support iOS 7 and hopefully we'll be able to move to XLData.

Since we use [XLDataLoader](https://github.com/xmartlabs/XLDataLoader) in several parts of the app I was wondering if there's a guide on how to make this transition.

Thank you.

**Comment by mtnbarreto** [comment]
It's not worth writing the migration guide since there are only few people using XLData. 
@ppaulojr Please feel free to ask if you need any help with this.
